---
seed: 1989

num_workers: 4
experiment_name: "training"
image_path: "artifacts/dataset:v7/images"
mask_path: "artifacts/dataset:v7/masks"
val_split: 0.2
max_supported_bs: 8

model:
  type: segmentation_models_pytorch.UnetPlusPlus
  encoder_name: resnet50
  classes: 1
  encoder_weights: imagenet


scheduler:
  type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2

train_parameters:
  batch_size: 2

checkpoint_callback:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "./cyst_checkpoints/Nature_v3"
  monitor: val_iou
  verbose: True
  mode: max
  save_top_k: 1
  
earlystopping_callback:
  type: pytorch_lightning.callbacks.early_stopping.EarlyStopping
  monitor: valid_loss
  min_delta: 0.001
  patience: 7
  verbose: True
  mode: min

val_parameters:
  batch_size: 2

optimizer:
  # type: adamp.AdamP
  type: torch.optim.Adam
  lr: 0.0001


train_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
        always_apply: False
        max_size: 800
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
        always_apply: false
        border_mode: 0
        mask_value: 0
        min_height: 800
        min_width: 800
        p: 1
        value: 0
#       - __class_fullname__: albumentations.augmentations.transforms.RandomCrop
#         always_apply: False
#         height: 512
#         width: 512
#         p: 1
#       - __class_fullname__: albumentations.augmentations.transforms.CropNonEmptyMaskIfExists
#         always_apply: false
#         height: 512
#         ignore_channels:
#           - 1
#         p: 1
#         width: 512
      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
        always_apply: False
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.RandomRotate90
        always_apply: False
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
        p: 1.0
      - __class_fullname__: albumentations.augmentations.transforms.RandomGamma
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.CLAHE
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

val_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
        always_apply: False
        max_size: 800
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
        always_apply: false
        border_mode: 0
        mask_value: 0
        min_height: 800
        min_width: 800
        p: 1
        value: 0
      - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
        p: 1.0
      - __class_fullname__: albumentations.augmentations.transforms.RandomGamma
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.CLAHE
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

test_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
        always_apply: False
        max_size: 800
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225
