---
seed: 7

num_workers: 0
test_experiment: 3

val_split: 0.2

model:
  type: segmentation_models_pytorch.UnetPlusPlus
  encoder_name: resnet50
  classes: 1
  encoder_weights: imagenet


scheduler:
  type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 10
  T_mult: 2

train_parameters:
  batch_size: 32
  preprocessing: False

checkpoint_callback:
  type: pytorch_lightning.callbacks.ModelCheckpoint
  filepath: "./cyst_checkpoints/prova1"
  monitor: val_iou
  verbose: True
  mode: max
  save_top_k: 3

val_parameters:
  batch_size: 2

optimizer:
  type: adamp.AdamP
  lr: 0.0001


train_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
        always_apply: false
        max_size: 512
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
        always_apply: false
        border_mode: 0
        mask_value: 0
        min_height: 512
        min_width: 512
        p: 1
        value: 0
      - __class_fullname__: albumentations.augmentations.transforms.CropNonEmptyMaskIfExists
        always_apply: false
        height: 512
        ignore_channels:
        - 1
        p: 1
        width: 512
      - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.RandomRotate90
        always_apply: False
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
        p: 1.0
      - __class_fullname__: albumentations.augmentations.transforms.RandomGamma
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.CLAHE
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
        - 0.485
        - 0.456
        - 0.406
        p: 1
        std:
        - 0.229
        - 0.224
        - 0.225


val_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
      - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
        always_apply: False
        max_size: 512
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.PadIfNeeded
        always_apply: False
        min_height: 512
        min_width: 512
        border_mode: 0
        value: 0
        mask_value: 0
        p: 1
      - __class_fullname__: albumentations.augmentations.transforms.RandomBrightnessContrast
        p: 1.0
      - __class_fullname__: albumentations.augmentations.transforms.RandomGamma
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.CLAHE
        always_apply: false
        p: 0.5
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225

test_aug:
  transform:
    __class_fullname__: albumentations.core.composition.Compose
    bbox_params: null
    keypoint_params: null
    p: 1
    transforms:
#       - __class_fullname__: albumentations.augmentations.transforms.LongestMaxSize
#         always_apply: False
#         max_size: 512
#         p: 1
      - __class_fullname__: albumentations.augmentations.transforms.Normalize
        always_apply: false
        max_pixel_value: 255.0
        mean:
          - 0.485
          - 0.456
          - 0.406
        p: 1
        std:
          - 0.229
          - 0.224
          - 0.225
