hardnet:
    train_parameters:
      batch_size: 16
    optimizer:
      lr: 0.0001
pranet:
    train_parameters:
      batch_size: 16
    optimizer:
      lr: 0.0007
uacanet:
    train_parameters:
      batch_size: 16
    optimizer:
      lr: 0.0001
