pranet:
  max_supported_bs: 8
  lr: 0.0017

unetpp:
  max_supported_bs: 4
  lr: 0.0001

unetplusplus:
  max_supported_bs: 4
  lr: 0.0001

unet:
  max_supported_bs: 8
  lr: 0.0004

hardnet: #still-todo
  max_supported_bs: 8
  lr: 0.0004
  
uacanet:
  batch_size: 4
  lr: 0.0001
