program: train.py
method: grid
metric:
  goal: maximize
  name: max_val_iou
parameters:
  config_path:
    value: configs/default.yaml
  batch_size:
    value: 16
  lr:
    values: [0.0005, 0.0001]
  model:
    values: [unet, upp]
  transf_onlycysts:
    values: [1, 0]
  transf_crop:
    values: [1, 2, 3, 4, 8]
  transf_enhancement:
    values: [1, 0]